// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raft.proto

/*
Package naive_raft is a generated protocol buffer package.

It is generated from these files:
	proto/raft.proto

It has these top-level messages:
	LogEntris
	AppendEntriesReq
	AppendEntriesResp
	CanvassReq
	CanvassResp
*/
package naive_raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEntris struct {
	Index int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Term  int32  `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *LogEntris) Reset()                    { *m = LogEntris{} }
func (m *LogEntris) String() string            { return proto.CompactTextString(m) }
func (*LogEntris) ProtoMessage()               {}
func (*LogEntris) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogEntris) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntris) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntris) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AppendEntriesReq struct {
	Term          int32        `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId      int32        `protobuf:"varint,2,opt,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex  int32        `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevTermIndex int32        `protobuf:"varint,4,opt,name=prevTermIndex" json:"prevTermIndex,omitempty"`
	LogEntris     []*LogEntris `protobuf:"bytes,5,rep,name=LogEntris" json:"LogEntris,omitempty"`
	LeaderCommit  int32        `protobuf:"varint,6,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
}

func (m *AppendEntriesReq) Reset()                    { *m = AppendEntriesReq{} }
func (m *AppendEntriesReq) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesReq) ProtoMessage()               {}
func (*AppendEntriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesReq) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevTermIndex() int32 {
	if m != nil {
		return m.PrevTermIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetLogEntris() []*LogEntris {
	if m != nil {
		return m.LogEntris
	}
	return nil
}

func (m *AppendEntriesReq) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResp struct {
	Term    int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResp) Reset()                    { *m = AppendEntriesResp{} }
func (m *AppendEntriesResp) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResp) ProtoMessage()               {}
func (*AppendEntriesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesResp) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CanvassReq struct {
	Term         int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId  int32 `protobuf:"varint,2,opt,name=candidateId" json:"candidateId,omitempty"`
	LastLogIndex int32 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  int32 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *CanvassReq) Reset()                    { *m = CanvassReq{} }
func (m *CanvassReq) String() string            { return proto.CompactTextString(m) }
func (*CanvassReq) ProtoMessage()               {}
func (*CanvassReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CanvassReq) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *CanvassReq) GetCandidateId() int32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *CanvassReq) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *CanvassReq) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type CanvassResp struct {
	Term         int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VotedGranted bool  `protobuf:"varint,2,opt,name=votedGranted" json:"votedGranted,omitempty"`
}

func (m *CanvassResp) Reset()                    { *m = CanvassResp{} }
func (m *CanvassResp) String() string            { return proto.CompactTextString(m) }
func (*CanvassResp) ProtoMessage()               {}
func (*CanvassResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CanvassResp) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *CanvassResp) GetVotedGranted() bool {
	if m != nil {
		return m.VotedGranted
	}
	return false
}

func init() {
	proto.RegisterType((*LogEntris)(nil), "naive_raft.LogEntris")
	proto.RegisterType((*AppendEntriesReq)(nil), "naive_raft.AppendEntriesReq")
	proto.RegisterType((*AppendEntriesResp)(nil), "naive_raft.AppendEntriesResp")
	proto.RegisterType((*CanvassReq)(nil), "naive_raft.CanvassReq")
	proto.RegisterType((*CanvassResp)(nil), "naive_raft.CanvassResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppendEntries service

type AppendEntriesClient interface {
	AppendEntriesRPC(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResp, error)
}

type appendEntriesClient struct {
	cc *grpc.ClientConn
}

func NewAppendEntriesClient(cc *grpc.ClientConn) AppendEntriesClient {
	return &appendEntriesClient{cc}
}

func (c *appendEntriesClient) AppendEntriesRPC(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResp, error) {
	out := new(AppendEntriesResp)
	err := grpc.Invoke(ctx, "/naive_raft.AppendEntries/AppendEntriesRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppendEntries service

type AppendEntriesServer interface {
	AppendEntriesRPC(context.Context, *AppendEntriesReq) (*AppendEntriesResp, error)
}

func RegisterAppendEntriesServer(s *grpc.Server, srv AppendEntriesServer) {
	s.RegisterService(&_AppendEntries_serviceDesc, srv)
}

func _AppendEntries_AppendEntriesRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendEntriesServer).AppendEntriesRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naive_raft.AppendEntries/AppendEntriesRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendEntriesServer).AppendEntriesRPC(ctx, req.(*AppendEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppendEntries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "naive_raft.AppendEntries",
	HandlerType: (*AppendEntriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntriesRPC",
			Handler:    _AppendEntries_AppendEntriesRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

// Client API for Canvass service

type CanvassClient interface {
	CanvassRPC(ctx context.Context, in *CanvassReq, opts ...grpc.CallOption) (*CanvassResp, error)
}

type canvassClient struct {
	cc *grpc.ClientConn
}

func NewCanvassClient(cc *grpc.ClientConn) CanvassClient {
	return &canvassClient{cc}
}

func (c *canvassClient) CanvassRPC(ctx context.Context, in *CanvassReq, opts ...grpc.CallOption) (*CanvassResp, error) {
	out := new(CanvassResp)
	err := grpc.Invoke(ctx, "/naive_raft.Canvass/CanvassRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Canvass service

type CanvassServer interface {
	CanvassRPC(context.Context, *CanvassReq) (*CanvassResp, error)
}

func RegisterCanvassServer(s *grpc.Server, srv CanvassServer) {
	s.RegisterService(&_Canvass_serviceDesc, srv)
}

func _Canvass_CanvassRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanvassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvassServer).CanvassRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naive_raft.Canvass/CanvassRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvassServer).CanvassRPC(ctx, req.(*CanvassReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Canvass_serviceDesc = grpc.ServiceDesc{
	ServiceName: "naive_raft.Canvass",
	HandlerType: (*CanvassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanvassRPC",
			Handler:    _Canvass_CanvassRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

func init() { proto.RegisterFile("proto/raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcb, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xff, 0xb9, 0x4f, 0x12, 0x48, 0x45, 0x2f, 0x26, 0xb4, 0x60, 0x44, 0x17, 0x59,
	0xa5, 0x90, 0x3c, 0x40, 0x09, 0x26, 0x94, 0x94, 0x2c, 0x52, 0xd3, 0x7d, 0x51, 0xa2, 0x69, 0x30,
	0xd4, 0xb2, 0x2b, 0xa9, 0xa6, 0x8f, 0xd0, 0x17, 0xed, 0x7b, 0x14, 0xcb, 0xae, 0x23, 0x9b, 0xa4,
	0x3b, 0xcd, 0x37, 0x9a, 0xf1, 0x39, 0x07, 0x19, 0x46, 0x89, 0x8c, 0x75, 0x7c, 0x27, 0xd9, 0xab,
	0x9e, 0x9a, 0x23, 0x01, 0xc1, 0xc2, 0x14, 0x5f, 0x32, 0x42, 0x57, 0xd0, 0x5b, 0xc7, 0xfb, 0xa5,
	0xd0, 0x32, 0x54, 0xe4, 0x1c, 0x5a, 0xa1, 0xe0, 0xf8, 0xe9, 0x3a, 0x9e, 0x33, 0x69, 0x05, 0x79,
	0x41, 0x08, 0x34, 0x35, 0xca, 0xc8, 0xfd, 0x6f, 0xa0, 0x39, 0x67, 0x8c, 0x33, 0xcd, 0xdc, 0x86,
	0xe7, 0x4c, 0x7a, 0x81, 0x39, 0xd3, 0x6f, 0x07, 0x46, 0x8b, 0x24, 0x41, 0xc1, 0xcd, 0x3a, 0x54,
	0x01, 0xbe, 0x97, 0xc3, 0x8e, 0x35, 0x3c, 0x86, 0xee, 0x1b, 0x32, 0x8e, 0x72, 0xc5, 0x8b, 0xa5,
	0x65, 0x4d, 0x28, 0x0c, 0x12, 0x89, 0xe9, 0x3a, 0xde, 0xaf, 0x8c, 0x92, 0x86, 0xe9, 0x57, 0x18,
	0xb9, 0x85, 0x61, 0x56, 0x3f, 0xa3, 0x8c, 0xf2, 0x4b, 0x4d, 0x73, 0xa9, 0x0a, 0xc9, 0xdc, 0x72,
	0xe6, 0xb6, 0xbc, 0xc6, 0xa4, 0x3f, 0xbb, 0x98, 0x1e, 0x9c, 0x4f, 0xcb, 0x66, 0x60, 0x25, 0x40,
	0x61, 0x90, 0x4b, 0xf1, 0xe3, 0x28, 0x0a, 0xb5, 0xdb, 0xce, 0x3f, 0x6f, 0x33, 0xba, 0x80, 0xb3,
	0x9a, 0x4d, 0x95, 0x1c, 0xf5, 0xe9, 0x42, 0x47, 0x7d, 0xec, 0x76, 0xa8, 0x94, 0xb1, 0xd9, 0x0d,
	0x7e, 0x4b, 0xfa, 0xe5, 0x00, 0xf8, 0x4c, 0xa4, 0x4c, 0x9d, 0x0c, 0xc9, 0x83, 0xfe, 0x8e, 0x09,
	0x1e, 0x72, 0xa6, 0xb1, 0xcc, 0xc9, 0x46, 0x46, 0x2b, 0x53, 0xba, 0x1e, 0x95, 0xcd, 0xb2, 0x2d,
	0x45, 0x9d, 0x05, 0x53, 0x04, 0x65, 0x23, 0xba, 0x84, 0x7e, 0xa9, 0xe4, 0x84, 0x0f, 0x0a, 0x83,
	0x34, 0xd6, 0xc8, 0x1f, 0x24, 0x13, 0x1a, 0x79, 0x61, 0xa6, 0xc2, 0x66, 0x5b, 0x18, 0x56, 0x42,
	0x21, 0x4f, 0xf5, 0xc7, 0xb0, 0xf1, 0xc9, 0xb5, 0x9d, 0x7f, 0xfd, 0xa9, 0x8c, 0x6f, 0xfe, 0xe8,
	0xaa, 0x84, 0xfe, 0x9b, 0x3d, 0x42, 0xa7, 0x90, 0x4a, 0xee, 0x0f, 0xf9, 0x6d, 0x7c, 0x72, 0x69,
	0x4f, 0x1e, 0x72, 0x1d, 0x5f, 0x1d, 0xe5, 0xd9, 0xae, 0x6d, 0xdb, 0xfc, 0x0a, 0xf3, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x54, 0x81, 0x34, 0xf7, 0x1e, 0x03, 0x00, 0x00,
}
